default_install_hook_types:
- pre-commit
repos:
- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
  - id: isort
    stages: [pre-commit]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.278
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
    stages: [pre-commit]
